// Generated by scripts/generate-codex-schema.mjs. Do not edit by hand.
import type { ApplyPatchApprovalParams } from "./generated/ApplyPatchApprovalParams";
import type { ApplyPatchApprovalResponse } from "./generated/ApplyPatchApprovalResponse";
import type { ExecCommandApprovalParams } from "./generated/ExecCommandApprovalParams";
import type { ExecCommandApprovalResponse } from "./generated/ExecCommandApprovalResponse";
import type { AttestationGenerateParams } from "./generated/v2/AttestationGenerateParams";
import type { AttestationGenerateResponse } from "./generated/v2/AttestationGenerateResponse";
import type { ChatgptAuthTokensRefreshParams } from "./generated/v2/ChatgptAuthTokensRefreshParams";
import type { ChatgptAuthTokensRefreshResponse } from "./generated/v2/ChatgptAuthTokensRefreshResponse";
import type { CommandExecutionRequestApprovalParams } from "./generated/v2/CommandExecutionRequestApprovalParams";
import type { CommandExecutionRequestApprovalResponse } from "./generated/v2/CommandExecutionRequestApprovalResponse";
import type { CurrentTimeReadParams } from "./generated/v2/CurrentTimeReadParams";
import type { CurrentTimeReadResponse } from "./generated/v2/CurrentTimeReadResponse";
import type { DynamicToolCallParams } from "./generated/v2/DynamicToolCallParams";
import type { DynamicToolCallResponse } from "./generated/v2/DynamicToolCallResponse";
import type { FileChangeRequestApprovalParams } from "./generated/v2/FileChangeRequestApprovalParams";
import type { FileChangeRequestApprovalResponse } from "./generated/v2/FileChangeRequestApprovalResponse";
import type { McpServerElicitationRequestParams } from "./generated/v2/McpServerElicitationRequestParams";
import type { McpServerElicitationRequestResponse } from "./generated/v2/McpServerElicitationRequestResponse";
import type { PermissionsRequestApprovalParams } from "./generated/v2/PermissionsRequestApprovalParams";
import type { PermissionsRequestApprovalResponse } from "./generated/v2/PermissionsRequestApprovalResponse";
import type { ToolRequestUserInputParams } from "./generated/v2/ToolRequestUserInputParams";
import type { ToolRequestUserInputResponse } from "./generated/v2/ToolRequestUserInputResponse";

export interface CodexServerRequestMethodMap {
  "item/commandExecution/requestApproval": { params: CommandExecutionRequestApprovalParams; result: CommandExecutionRequestApprovalResponse };
  "item/fileChange/requestApproval": { params: FileChangeRequestApprovalParams; result: FileChangeRequestApprovalResponse };
  "item/tool/requestUserInput": { params: ToolRequestUserInputParams; result: ToolRequestUserInputResponse };
  "mcpServer/elicitation/request": { params: McpServerElicitationRequestParams; result: McpServerElicitationRequestResponse };
  "item/permissions/requestApproval": { params: PermissionsRequestApprovalParams; result: PermissionsRequestApprovalResponse };
  "item/tool/call": { params: DynamicToolCallParams; result: DynamicToolCallResponse };
  "account/chatgptAuthTokens/refresh": { params: ChatgptAuthTokensRefreshParams; result: ChatgptAuthTokensRefreshResponse };
  "attestation/generate": { params: AttestationGenerateParams; result: AttestationGenerateResponse };
  "currentTime/read": { params: CurrentTimeReadParams; result: CurrentTimeReadResponse };
  "applyPatchApproval": { params: ApplyPatchApprovalParams; result: ApplyPatchApprovalResponse };
  "execCommandApproval": { params: ExecCommandApprovalParams; result: ExecCommandApprovalResponse };
}
