import { mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { app, BrowserWindow, clipboard, dialog, ipcMain, shell } from 'electron';
import {
  installCodexWindowPolicy,
  isCodexRendererSender,
  registerCodexElectronMain,
} from '@codex-app-sdk/electron';
import { createCodexAppBackend, type CodexAppBackend } from '@codex-app-sdk/backend';
import { initializeRelayState, readRelayState, resetRelayState } from '../mcp/relay-store';
import { RELAY_RESET_CHANNEL, RELAY_SNAPSHOT_CHANNEL } from '../shared/relay-contracts';

const bundleDirectory = path.dirname(fileURLToPath(import.meta.url));
const devServerUrl = process.env.VITE_DEV_SERVER_URL?.trim();
const rendererFile = path.join(bundleDirectory, '../dist-renderer/index.html');
// The window may only show this renderer, and only this renderer may call the Codex bridge.
const rendererUrl = devServerUrl || pathToFileURL(rendererFile).href;
const isTrustedSender = (event: unknown) => isCodexRendererSender(event, rendererUrl);
let mainWindow: BrowserWindow | null = null;
let backend: CodexAppBackend | null = null;
let unregisterSdk: (() => void) | null = null;
let relayIpcRegistered = false;

app.setName('Relay');

async function createWindow(): Promise<void> {
  mainWindow = new BrowserWindow({
    width: 1440,
    height: 920,
    minWidth: 980,
    minHeight: 720,
    backgroundColor: '#f7f7f5',
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
      preload: path.join(bundleDirectory, 'preload.cjs'),
    },
  });
  installCodexWindowPolicy(mainWindow.webContents, {
    rendererUrl,
    // Relay only hands HTTPS links to the system browser.
    openExternal: async (url) => { if (url.startsWith('https:')) await shell.openExternal(url); },
  });
  if (devServerUrl) {
    await mainWindow.loadURL(devServerUrl);
  } else {
    await mainWindow.loadFile(rendererFile);
  }
  mainWindow.on('closed', () => { mainWindow = null; });
}

app.whenReady().then(async () => {
  const appData = app.getPath('userData');
  const codexHome = path.join(app.getPath('home'), '.codex-relay');
  const workspace = path.join(appData, 'workspace');
  const statePath = path.join(appData, 'relay-operations.json');
  const mcpServerPath = path.join(bundleDirectory, '../dist-mcp/server.js');
  await Promise.all([
    mkdir(codexHome, { recursive: true }),
    mkdir(workspace, { recursive: true }),
    initializeRelayState(statePath),
  ]);

  const sdkBackend = createCodexAppBackend({
    surfaceOptions: {
      approvalPreset: 'ask-for-approval',
      autoSelectFirstConversation: true,
      clientInfo: { name: 'relay', title: 'Relay', version: '0.1.0' },
      codexHome,
      conversationLimit: 1,
      cwd: workspace,
      mcpServers: [{
        name: 'relay',
        transport: {
          type: 'stdio',
          command: process.execPath,
          args: [mcpServerPath],
          cwd: path.dirname(mcpServerPath),
          env: {
            ELECTRON_RUN_AS_NODE: '1',
            RELAY_STATE_PATH: statePath,
          },
        },
        toolApprovalMode: 'writes',
        required: true,
        enabledTools: [
          'list_exceptions',
          'get_shipment',
          'find_recovery_options',
          'draft_customer_update',
          'rebook_shipment',
        ],
        startupTimeoutMs: 10_000,
        toolTimeoutMs: 30_000,
      }],
      extensions: [{
        configureConversation: () => ({
          developerInstructions: [
            'You are the operations copilot embedded in Relay, a logistics exception desk.',
            'Use the relay MCP server as the authoritative source for shipment state.',
            'A prompt generated by a business-view click explains the user intent and the snapshot they saw; retrieve live state before answering.',
            'Keep operational answers concise, identify tradeoffs explicitly, and prefer concrete next actions.',
            'Never call rebook_shipment until the user explicitly approves a named recovery option.',
            'After any mutation, confirm what changed and mention that the operations view has refreshed.',
          ].join(' '),
        }),
      }],
      permissionMode: 'read-only',
    },
    modules: [{
      id: 'relay.operations',
      create: () => ({
        readSnapshot: () => readRelayState(statePath),
        resetDemo: () => resetRelayState(statePath),
      }),
    }],
  });
  backend = sdkBackend;
  const relayOperations = sdkBackend.module<{
    readSnapshot: () => ReturnType<typeof readRelayState>;
    resetDemo: () => ReturnType<typeof resetRelayState>;
  }>('relay.operations');
  unregisterSdk = registerCodexElectronMain({
    clipboard,
    dialog,
    ipcMain,
    isTrustedSender,
    shell,
    surface: sdkBackend.surface,
    sender: { send: (channel, payload) => mainWindow?.webContents.send(channel, payload) },
  });
  if (!relayIpcRegistered) {
    ipcMain.handle(RELAY_SNAPSHOT_CHANNEL, (event) => {
      assertTrustedSender(event);
      return relayOperations.readSnapshot();
    });
    ipcMain.handle(RELAY_RESET_CHANNEL, (event) => {
      assertTrustedSender(event);
      return relayOperations.resetDemo();
    });
    relayIpcRegistered = true;
  }
  await createWindow();
  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) void createWindow();
  });
});

function assertTrustedSender(event: unknown): void {
  if (!isTrustedSender(event)) throw new Error('Rejected Relay IPC from an untrusted sender');
}

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});

app.on('before-quit', () => {
  unregisterSdk?.();
  unregisterSdk = null;
  if (relayIpcRegistered) {
    ipcMain.removeHandler(RELAY_SNAPSHOT_CHANNEL);
    ipcMain.removeHandler(RELAY_RESET_CHANNEL);
    relayIpcRegistered = false;
  }
  void backend?.close().catch(() => undefined);
  backend = null;
});
